# -*- coding: utf-8 -*-
"""ĐỀ KIỂM TRA GIỮA KỲ I - VẬT LÍ 10 - THPT NGUYỄN TRƯỜNG TỘ (HUẾ) - MÃ ĐỀ 102
Nguồn: De_Goc/2026-Dethi-GHK1-10/VL10-GHKI-NTT-2526.tex
Bản quyền: LỚP TOÁN CÔ THÚY - GV: HỒ THỊ THÚY"""
import vl10_engine as E

P1 = [
    dict(stem=r"Công thức tính vận tốc của chuyển động thẳng biến đổi đều là $v = v_0 + at$. Đối với chuyển động thẳng nhanh dần đều thì ta luôn có",
         opts=[r"$v$ luôn dương.",
               r"$a$ luôn dương.",
               r"$a$ luôn cùng dấu với $v$.",
               r"$a$ luôn ngược dấu với $v$."], ans=2,
         sol=[r"Trong chuyển động thẳng nhanh dần đều, vectơ gia tốc $\vec{a}$ luôn cùng hướng với vectơ vận tốc $\vec{v}$, do đó $a$ và $v$ luôn cùng dấu ($a \cdot v > 0$)."]),
    dict(stem=r"Đặc điểm nào sau đây \textbf{không} phải là tính chất của vectơ vận tốc trong chuyển động thẳng của một chất điểm?",
         opts=[r"Gốc nằm trên chất điểm chuyển động.",
               r"Phương trùng với phương chuyển động của chất điểm.",
               r"Có chiều luôn ngược với chiều chuyển động của chất điểm.",
               r"Độ dài tỉ lệ với độ lớn của vận tốc theo một tỉ xích quy ước."], ans=2,
         sol=[r"Vectơ vận tốc $\vec{v}$ luôn có hướng (gồm phương và chiều) trùng với hướng chuyển động của chất điểm. Phát biểu C nói chiều ngược với chiều chuyển động là sai."]),
    dict(stem=r"Chọn phát biểu đúng khi nói về quãng đường đi được của một vật chuyển động.",
         opts=[r"Quãng đường là một đại lượng vô hướng luôn nhận giá trị không âm ($s \ge 0$).",
               r"Quãng đường luôn luôn nhận giá trị âm.",
               r"Quãng đường là một đại lượng vectơ xác định hướng chuyển động.",
               r"Quãng đường có thể nhận giá trị âm hoặc dương tùy thuộc vào chiều dương được chọn."], ans=0,
         sol=[r"Quãng đường đi được $s$ là độ dài cung đường mà vật vạch ra trong quá trình chuyển động, là đại lượng vô hướng và luôn không âm ($s \ge 0$)."]),
    dict(stem=r"Gọi $\overline{A}$ là giá trị trung bình, $\Delta A'$ là sai số dụng cụ, $\overline{\Delta A}$ là sai số ngẫu nhiên tuyệt đối. Công thức tính sai số tuyệt đối toàn phần $\Delta A$ của phép đo trực tiếp là",
         opts=[r"$\Delta A = \overline{\Delta A} + \Delta A'$.",
               r"$\Delta A = \overline{\Delta A} - \Delta A'$.",
               r"$\Delta A = \overline{\Delta A} \cdot \Delta A'$.",
               r"$\Delta A = \overline{\Delta A} / \Delta A'$."], ans=0,
         sol=[r"Sai số tuyệt đối toàn phần của một phép đo trực tiếp bằng tổng của sai số ngẫu nhiên và sai số dụng cụ: $\Delta A = \overline{\Delta A} + \Delta A'$."]),
    dict(stem=r"Một vật chuyển động trên đường thẳng có vận tốc $v$ và gia tốc $a$. Chuyển động của vật là chuyển động chậm dần đều khi",
         opts=[r"gia tốc $a < 0$.",
               r"gia tốc $a > 0$.",
               r"tích số $a \cdot v < 0$.",
               r"vận tốc $v < 0$."], ans=2,
         sol=[r"Chuyển động thẳng là chậm dần đều khi vectơ gia tốc ngược hướng với vectơ vận tốc, tương ứng tích số giữa hai giá trị đại số mang dấu âm: $a \cdot v < 0$."]),
    dict(stem=r"Những phân ngành nào sau đây thuộc về các lĩnh vực nghiên cứu nền tảng của khoa học Vật lí cổ điển?",
         opts=[r"Cơ học, nhiệt học, cấu trúc tiến hóa của vật chất vô cơ.",
               r"Nhiệt học, quang học, cơ chế di truyền của sinh vật học.",
               r"Cơ học, nhiệt học, điện học, quang học.",
               r"Điện học, quang học, tính chất hóa học của hợp chất."], ans=2,
         sol=[r"Cơ học, nhiệt học, điện học và quang học là bốn phân ngành nền tảng cốt lõi của Vật lí học cổ điển."]),
    dict(stem=r"Biển báo dùng để cảnh báo nguy cơ gây ô nhiễm nguy hiểm đối với môi trường sinh thái là biển báo nào trong hình dưới đây?",
         fig=("fig_cau7_bienbao", 12.0),
         opts=[r"Hình 1 (Chất độc cấp tính).",
               r"Hình 2 (Chất ăn mòn).",
               r"Hình 3 (Nguy cơ điện giật).",
               r"Hình 4 (Nguy hại môi trường)."], ans=3,
         sol=[r"Biển báo Hình 4 (biểu tượng cây khô trơ trụi và cá chết) là kí hiệu tiêu chuẩn cảnh báo chất độc nguy hại đối với môi trường sinh thái."]),
    dict(stem=r"Một người chạy bộ dọc theo một đường thẳng, trong khoảng thời gian $10\text{ s}$ người đó chạy được quãng đường $150\text{ m}$. Tốc độ trung bình của người đó là",
         opts=[r"$150\text{ m/s}$.",
               r"$0{,}015\text{ m/s}$.",
               r"$15\text{ m/s}$.",
               r"$15\text{ km/s}$."], ans=2,
         sol=[r"Tốc độ trung bình:",
              r"\[v_{\text{tb}} = \frac{s}{t} = \frac{150}{10} = 15\text{ m/s}.\]"]),
    dict(stem=r"Một ô tô đang chuyển động thẳng đều thì hãm phanh để dừng lại. Chọn chiều dương là chiều chuyển động của xe. Nhận xét nào sau đây đúng về dấu của vận tốc $v$ và gia tốc $a$?",
         opts=[r"$a > 0,\ v > 0$.",
               r"$a < 0,\ v < 0$.",
               r"$a > 0,\ v < 0$.",
               r"$a < 0,\ v > 0$."], ans=3,
         sol=[r"-- Xe chuyển động theo chiều dương nên $v > 0$.",
              r"-- Xe hãm phanh chuyển động chậm dần đều nên gia tốc ngược chiều vận tốc, suy ra $a < 0$."]),
    dict(stem=r"Chọn mốc thời gian là lúc $t_0 = 8\text{ h}$. Một chuyển động kéo dài trong khoảng thời gian $\Delta t = 3\text{ h}$. Thời điểm kết thúc chuyển động là lúc",
         opts=[r"$8\text{ h}$.",
               r"$10\text{ h}$.",
               r"$11\text{ h}$.",
               r"$12\text{ h}$."], ans=2,
         sol=[r"Thời điểm kết thúc: $t = t_0 + \Delta t = 8\text{ h} + 3\text{ h} = 11\text{ h}$."]),
    dict(stem=r"Đồ thị độ dịch chuyển -- thời gian $(d - t)$ của một xe chuyển động thẳng có dạng đường thẳng dốc xuống từ vạch $80\text{ km}$ về vạch $0\text{ km}$ trong thời gian $2\text{ h}$ như đường (2) ở hình bên. Kết luận nào sau đây đúng?",
         fig=("fig_dothi_xe12", 6.5),
         opts=[r"Vật chuyển động thẳng đều ngược chiều dương với tốc độ $40\text{ km/h}$.",
               r"Vật chuyển động thẳng đều cùng chiều dương với tốc độ $20\text{ km/h}$.",
               r"Vật chuyển động thẳng đều ngược chiều dương với tốc độ $60\text{ km/h}$.",
               r"Vật chuyển động thẳng đều cùng chiều dương với tốc độ $40\text{ km/h}$."], ans=0,
         sol=[r"-- Đồ thị dốc xuống cho thấy độ dịch chuyển giảm theo thời gian, vật chuyển động ngược chiều dương.",
              r"-- Tốc độ của vật: $v = \dfrac{|\Delta d|}{\Delta t} = \dfrac{|0 - 80|}{2} = 40\text{ km/h}$."]),
    dict(stem=r"Khi được thả rơi cùng một lúc từ cùng một độ cao trong không khí, chuyển động của vật nào sau đây được coi gần đúng là rơi tự do?",
         opts=[r"Một chiếc khăn voan mỏng nhẹ.",
               r"Một sợi chỉ mảnh dài.",
               r"Một chiếc lá cây khô đang rụng.",
               r"Một viên sỏi nhỏ đặc."], ans=3,
         sol=[r"Viên sỏi nhỏ đặc có khối lượng riêng lớn, lực cản của không khí tác dụng lên nó là không đáng kể so với trọng lượng, nên chuyển động của nó được coi gần đúng là sự rơi tự do."]),
]

P2 = [
    dict(stem=r"Hình bên mô tả đồ thị độ dịch chuyển -- thời gian $(d - t)$ của hai xe 1 và xe 2 cùng chuyển động thẳng dọc theo trục tọa độ $Ox$.",
         fig=("fig_dothi_xe12", 6.5),
         items=[r"Trong khoảng thời gian từ $1\text{ h}$ đến $2\text{ h}$, xe 1 đứng yên không chuyển động.",
                r"Xe 2 luôn duy trì chuyển động thẳng đều theo chiều dương trong suốt khoảng thời gian từ $0\text{ h}$ đến $2\text{ h}$.",
                r"Trong khoảng thời gian từ $1\text{ h}$ đến $2\text{ h}$, xe 1 và xe 2 chuyển động với cùng vận tốc.",
                r"Trong khoảng thời gian từ $0\text{ h}$ đến $1\text{ h}$, xe 1 chuyển động thẳng đều theo chiều dương với tốc độ $20\text{ km/h}$."],
         truth=[True, False, False, True],
         sols=[r"Từ $1\text{ h}$ đến $2\text{ h}$, đường (1) nằm ngang song song trục thời gian ở $d = 40\text{ km}$, chứng tỏ xe 1 đứng yên.",
               r"Đường (2) dốc xuống từ $80\text{ km}$ về $0\text{ km}$, chứng tỏ xe 2 chuyển động ngược chiều dương.",
               r"Từ $1\text{ h}$ đến $2\text{ h}$, xe 1 đứng yên ($v_1 = 0$) còn xe 2 vẫn chuyển động ngược chiều dương ($v_2 = -40\text{ km/h}$), do đó vận tốc khác nhau.",
               r"Từ $0\text{ h}$ đến $1\text{ h}$, xe 1 đi từ $d = 20\text{ km}$ đến $d = 40\text{ km}$. Vận tốc $v = \dfrac{40 - 20}{1} = 20\text{ km/h} > 0$."]),
    dict(stem=r"Một vật nặng được thả rơi tự do từ trạng thái nghỉ tại độ cao $45\text{ m}$ so với mặt đất. Bỏ qua lực cản của không khí và lấy gia tốc trọng trường $g = 10\text{ m/s}^2$.",
         items=[r"Phương chuyển động rơi của vật luôn hướng theo phương thẳng đứng.",
                r"Thời gian rơi toàn phần để vật chạm đất bằng $2{,}5\text{ s}$.",
                r"Quãng đường vật rơi được sau $2\text{ s}$ đầu tiên kể từ lúc thả bằng $20\text{ m}$.",
                r"Thời gian vật rơi trong $13{,}75\text{ m}$ cuối cùng ngay trước khi chạm đất bằng $0{,}5\text{ s}$."],
         truth=[True, False, True, True],
         sols=[r"Chuyển động rơi tự do có phương thẳng đứng, chiều từ trên xuống dưới.",
               r"Thời gian rơi chạm đất: $t = \sqrt{\dfrac{2h}{g}} = \sqrt{\dfrac{2 \cdot 45}{10}} = 3\text{ s} \ne 2{,}5\text{ s}$.",
               r"Quãng đường sau $2\text{ s}$ đầu: $s = \dfrac{1}{2}gt^2 = \dfrac{1}{2} \cdot 10 \cdot 2^2 = 20\text{ m}$.",
               r"Vật rơi $45 - 13{,}75 = 31{,}25\text{ m}$ đầu tiên mất thời gian $t_1 = \sqrt{\dfrac{2 \cdot 31{,}25}{10}} = 2{,}5\text{ s}$. Do đó thời gian rơi đoạn cuối là $\Delta t = 3 - 2{,}5 = 0{,}5\text{ s}$."]),
]

P3 = [
    dict(stem=r"Một ô tô chuyển động thẳng nhanh dần đều. Sau thời gian $\Delta t = 8\text{ s}$, vận tốc của ô tô tăng đều từ $5\text{ m/s}$ đến $9\text{ m/s}$. Tính quãng đường mà ô tô đi được trong khoảng thời gian trên theo đơn vị kilômét (km)?",
         ans="0,056",
         sol=[r"Gia tốc của ô tô: $a = \dfrac{v - v_0}{\Delta t} = \dfrac{9 - 5}{8} = 0{,}5\text{ m/s}^2$.",
              r"Quãng đường ô tô đi được theo đơn vị mét:",
              r"\[s = v_0 t + \frac{1}{2}at^2 = 5 \cdot 8 + \frac{1}{2} \cdot 0{,}5 \cdot 8^2 = 40 + 16 = 56\text{ m}.\]",
              r"Đổi sang kilômét: $s = \dfrac{56}{1000} = 0{,}056\text{ km}$."]),
    dict(stem=r"Một ô tô di chuyển chặng thứ nhất đi được quãng đường $24\text{ km}$ về hướng Đông, sau đó rẽ sang hướng Bắc chạy tiếp một đoạn $7\text{ km}$ thì dừng lại. Độ lớn độ dịch chuyển tổng hợp của ô tô sau cả hai chặng là bao nhiêu kilômét (km)?",
         ans="25",
         sol=[r"Hai hướng chuyển động Đông và Bắc vuông góc với nhau.",
              r"Độ lớn độ dịch chuyển tổng hợp:",
              r"\[d = \sqrt{d_1^2 + d_2^2} = \sqrt{24^2 + 7^2} = \sqrt{576 + 49} = \sqrt{625} = 25\text{ km}.\]"]),
    dict(stem=r"Một vật được thả rơi tự do từ một độ cao $h$ xuống mặt đất. Lấy $g = 10\text{ m/s}^2$. Trong $1\text{ s}$ cuối cùng ngay trước khi chạm đất, vật rơi được quãng đường $25\text{ m}$. Thời gian rơi toàn phần của vật cho đến khi chạm đất là bao nhiêu giây?",
         ans="3",
         sol=[r"Gọi $t$ là tổng thời gian rơi chạm đất của vật ($t > 1\text{ s}$).",
              r"Quãng đường vật rơi trong $1\text{ s}$ cuối cùng:",
              r"\[\Delta s = s(t) - s(t - 1) = \frac{1}{2}gt^2 - \frac{1}{2}g(t - 1)^2 = g\left(t - 0{,}5\right).\]",
              r"Thay số: $25 = 10(t - 0{,}5) \Rightarrow t - 0{,}5 = 2{,}5 \Rightarrow t = 3\text{ s}$."]),
    dict(stem=r"Một người đi xe máy đang chuyển động thẳng đều với vận tốc $12\text{ m/s}$ thì hãm phanh. Xe chuyển động thẳng chậm dần đều rồi dừng lại sau khi đi thêm được đoạn đường $7{,}2\text{ m}$. Chọn chiều dương là chiều chuyển động, gia tốc của xe máy bằng bao nhiêu $\text{m/s}^2$?",
         ans="-10",
         sol=[r"Vận tốc đầu $v_0 = 12\text{ m/s}$, vận tốc cuối khi dừng hẳn $v = 0$.",
              r"Áp dụng hệ thức liên hệ độc lập thời gian:",
              r"\[v^2 - v_0^2 = 2as \Rightarrow 0^2 - 12^2 = 2 \cdot a \cdot 7{,}2 \Rightarrow -144 = 14{,}4a \Rightarrow a = -10\text{ m/s}^2.\]"]),
]

P4 = [
    dict(stem=r"Một chiếc thuyền máy chuyển động trên một dòng sông từ bến $A$ đến bến $B$ cách nhau $6\text{ km}$, sau đó quay đầu chạy ngược dòng từ $B$ về lại bến $A$. Tổng thời gian cả đi lẫn về là $2\text{ giờ } 30\text{ phút}$. Biết vận tốc của dòng nước đối với bờ sông ổn định và bằng $5\text{ km/h}$.",
         parts=[r"Tính vận tốc của thuyền máy đối với dòng nước (theo đơn vị $\text{km/h}$, làm tròn đến hai chữ số thập phân).",
                r"Hỏi khi thuyền đi xuôi dòng nước mất khoảng thời gian bao nhiêu giờ (làm tròn đến hai chữ số thập phân)?"],
         sol=[r"Đổi: $2\text{ giờ } 30\text{ phút} = 2{,}5\text{ h}$.",
              r"\textbf{a)} Gọi $v$ là vận tốc của thuyền máy đối với dòng nước ($v > 5\text{ km/h}$).",
              r"-- Vận tốc khi xuôi dòng: $v_1 = v + 5\text{ (km/h)}$; thời gian xuôi dòng: $t_1 = \dfrac{6}{v + 5}\text{ (h)}$.",
              r"-- Vận tốc khi ngược dòng: $v_2 = v - 5\text{ (km/h)}$; thời gian ngược dòng: $t_2 = \dfrac{6}{v - 5}\text{ (h)}$.",
              r"Phương trình tổng thời gian chuyển động:",
              r"\[t_1 + t_2 = 2{,}5 \Rightarrow \frac{6}{v + 5} + \frac{6}{v - 5} = 2{,}5 \Rightarrow \frac{12v}{v^2 - 25} = 2{,}5.\]",
              r"\[\Rightarrow 2{,}5v^2 - 12v - 62{,}5 = 0 \Leftrightarrow 5v^2 - 24v - 125 = 0.\]",
              r"Giải phương trình bậc hai với điều kiện $v > 5$, ta nhận nghiệm dương:",
              r"\[v = \frac{12 + \sqrt{12^2 - 5 \cdot (-125)}}{5} = \frac{12 + \sqrt{769}}{5} \approx 7{,}95\text{ km/h}.\]",
              r"\textbf{b)} Thời gian thuyền máy đi xuôi dòng nước:",
              r"\[t_1 = \frac{6}{v + 5} \approx \frac{6}{7{,}95 + 5} = \frac{6}{12{,}95} \approx 0{,}46\text{ h} \text{ (khoảng } 27{,}8\text{ phút)}.\]"]),
    dict(stem=r"Bảng số liệu dưới đây ghi lại thời gian rơi tự do của một vật giữa hai điểm cố định trong phòng thí nghiệm qua 5 lần đo:",
         parts=[r"Tính giá trị trung bình $\overline{t}$ của thời gian rơi.",
                r"Xác định sai số tuyệt đối trung bình $\overline{\Delta t}$ của phép đo."],
         sol=[r"\begin{center}\begin{tabular}{|c|c|c|c|c|c|}\hline \textbf{Lần đo} & \textbf{Lần 1} & \textbf{Lần 2} & \textbf{Lần 3} & \textbf{Lần 4} & \textbf{Lần 5} \\ \hline \textbf{Thời gian rơi (s)} & 0{,}315 & 0{,}318 & 0{,}316 & 0{,}317 & 0{,}319 \\ \hline\end{tabular}\end{center}",
              r"\textbf{a)} Giá trị trung bình của thời gian rơi qua 5 lần đo:",
              r"\[\overline{t} = \frac{0{,}315 + 0{,}318 + 0{,}316 + 0{,}317 + 0{,}319}{5} = \frac{1{,}585}{5} = 0{,}317\text{ s}.\]",
              r"\textbf{b)} Sai số tuyệt đối của từng lần đo:",
              r"\[\Delta t_1 = |0{,}317 - 0{,}315| = 0{,}002\text{ s}; \quad \Delta t_2 = |0{,}317 - 0{,}318| = 0{,}001\text{ s};\]",
              r"\[\Delta t_3 = |0{,}317 - 0{,}316| = 0{,}001\text{ s}; \quad \Delta t_4 = |0{,}317 - 0{,}317| = 0{,}000\text{ s}; \quad \Delta t_5 = |0{,}317 - 0{,}319| = 0{,}002\text{ s}.\]",
              r"Sai số tuyệt đối trung bình của phép đo:",
              r"\[\overline{\Delta t} = \frac{0{,}002 + 0{,}001 + 0{,}001 + 0{,}000 + 0{,}002}{5} = \frac{0{,}006}{5} = 0{,}0012\text{ s}.\]"]),
    dict(stem=r"Một vật bắt đầu chuyển động thẳng nhanh dần đều từ trạng thái nghỉ ($v_0 = 0$). Sau thời gian $3\text{ s}$ kể từ lúc xuất phát, vật đi được quãng đường $9\text{ m}$. Hãy xác định:",
         parts=[r"Gia tốc $a$ của chuyển động.",
                r"Thời gian kể từ lúc xuất phát để vật đạt vận tốc $15\text{ m/s}$."],
         sol=[r"\textbf{a)} Quãng đường vật đi được từ trạng thái nghỉ: $s = \dfrac{1}{2}at^2$.",
              r"Thay $s = 9\text{ m}$ và $t = 3\text{ s}$:",
              r"\[9 = \frac{1}{2}a \cdot 3^2 \Rightarrow 4{,}5a = 9 \Rightarrow a = 2\text{ m/s}^2.\]",
              r"\textbf{b)} Công thức vận tốc: $v = at = 2t$.",
              r"Khi vật đạt vận tốc $v = 15\text{ m/s}$:",
              r"\[15 = 2t \Rightarrow t = 7{,}5\text{ s}.\]"]),
]

if __name__ == "__main__":
    E.run(dict(FOLDER="NTT_10", MADE="102", PREFIX="VL10_NTT", SCHOOL="THPT NGUYỄN TRƯỜNG TỘ",
               YEAR="2025 -- 2026", YEAR_W="2025 – 2026", P1=P1, P2=P2, P3=P3, P4=P4))
