# -*- coding: utf-8 -*-
"""ĐỀ KIỂM TRA GIỮA KỲ I - VẬT LÍ 10 - THPT BÙI THỊ XUÂN (HUẾ) - MÃ ĐỀ 207
Nguồn: De_Goc/2026-Dethi-GHK1-10/VL10-GHKI-BTX-2526.tex
Bản quyền: LỚP TOÁN CÔ THÚY - GV: HỒ THỊ THÚY"""
import vl10_engine as E

P1 = [
    dict(stem=r"Trong hệ đơn vị SI, đơn vị của gia tốc là",
         opts=[r"$\text{m}\cdot\text{s}^2$", r"$\text{m}\cdot\text{s}$", r"$\text{m}\cdot\text{s}^{-1}$", r"$\text{m}\cdot\text{s}^{-2}$"], ans=3,
         sol=[r"Đơn vị của gia tốc trong hệ SI là mét trên giây bình phương: $\text{m/s}^2 = \text{m}\cdot\text{s}^{-2}$."]),
    dict(stem=r"Đồng hồ đo thời gian hiện số MC964 khi đặt ở chế độ MODE A $+$ B dùng để",
         opts=[r"đo thời gian vật chắn cổng quang điện nối với ổ B.",
               r"đo tổng hai khoảng thời gian vật chắn cổng quang điện nối với ổ A và cổng quang điện nối với ổ B.",
               r"đo thời gian vật chuyển động từ cổng quang điện nối với ổ A tới cổng quang điện nối với ổ B.",
               r"đo thời gian vật chắn cổng quang điện nối với ổ A."], ans=1,
         sol=[r"Ở chế độ MODE A $+$ B, đồng hồ đo tổng thời gian vật chắn cổng quang A và thời gian vật chắn cổng quang B: $\Delta t = \Delta t_A + \Delta t_B$."]),
    dict(stem=r"Chọn phát biểu đúng về vận tốc.",
         opts=[r"Vận tốc là đại lượng vô hướng, luôn có giá trị không âm.",
               r"Vận tốc là đại lượng vectơ, có hướng ngược với hướng của độ dịch chuyển.",
               r"Vận tốc là đại lượng vô hướng, có thể nhận giá trị âm hoặc dương.",
               r"Vận tốc là đại lượng vectơ, có hướng trùng với hướng của độ dịch chuyển."], ans=3,
         sol=[r"Vận tốc $\vec{v} = \dfrac{\vec{d}}{\Delta t}$ là đại lượng vectơ; vì $\Delta t > 0$ nên $\vec{v}$ cùng hướng với độ dịch chuyển $\vec{d}$."]),
    dict(stem=r"Đối tượng nghiên cứu của Vật lí là",
         opts=[r"các dạng vận động của vật chất và năng lượng.", r"sự phát triển sinh học của vật chất hữu cơ.",
               r"sự hình thành và phát triển của các lí thuyết vật lí.", r"cuộc đời và sự nghiệp của các nhà vật lí."], ans=0,
         sol=[r"Vật lí nghiên cứu các dạng vận động của vật chất (cơ, nhiệt, điện, từ, quang, hạt nhân,\ldots) và năng lượng."]),
    dict(stem=r"Chuyển động nào sau đây được coi là rơi tự do?",
         opts=[r"Vận động viên đang nhảy dù từ máy bay xuống.", r"Viên sỏi nhỏ được thả rơi từ trên cao trong không khí.",
               r"Chiếc lá khô đang rơi từ trên cành xuống.", r"Sợi chỉ mảnh được thả rơi trong không khí."], ans=1,
         sol=[r"Vật được coi là rơi tự do khi lực cản của không khí rất nhỏ so với trọng lượng. Viên sỏi nhỏ, nặng thỏa mãn điều kiện này; dù, lá khô, sợi chỉ chịu lực cản lớn."]),
    dict(stem=r"Phát biểu nào sau đây về chuyển động thẳng biến đổi đều là \textbf{sai}?",
         opts=[r"Trong chuyển động nhanh dần đều, vectơ gia tốc cùng chiều với chiều chuyển động.",
               r"Trong chuyển động thẳng biến đổi đều, gia tốc không đổi theo thời gian.",
               r"Trong chuyển động chậm dần đều, gia tốc luôn có giá trị âm.",
               r"Trong chuyển động chậm dần đều, vectơ gia tốc ngược chiều với chiều chuyển động."], ans=2,
         sol=[r"Trong chuyển động chậm dần đều, $\vec{a}$ ngược chiều $\vec{v}$ (tức $a \cdot v < 0$). Nếu vật chuyển động theo chiều âm ($v < 0$) thì $a > 0$. Vậy khẳng định gia tốc ``luôn có giá trị âm'' là sai."]),
    dict(stem=r"Gọi $\overline{A}$ là giá trị trung bình, $\Delta A'$ là sai số dụng cụ, $\overline{\Delta A}$ là sai số ngẫu nhiên và $\Delta A = \overline{\Delta A} + \Delta A'$ là sai số tuyệt đối của phép đo đại lượng $A$. Sai số tỉ đối của phép đo là",
         opts=[r"$\delta A = \dfrac{\overline{\Delta A}}{\overline{A}} \cdot 100\%$", r"$\delta A = \dfrac{\overline{A}}{\overline{\Delta A}} \cdot 100\%$",
               r"$\delta A = \dfrac{\Delta A'}{\overline{A}} \cdot 100\%$", r"$\delta A = \dfrac{\Delta A}{\overline{A}} \cdot 100\%$"], ans=3,
         sol=[r"Sai số tỉ đối bằng tỉ số giữa sai số tuyệt đối (toàn phần) và giá trị trung bình: $\delta A = \dfrac{\Delta A}{\overline{A}} \cdot 100\%$."]),
    dict(stem=r"Đồ thị độ dịch chuyển -- thời gian $(d - t)$ của chuyển động thẳng đều có dạng là",
         opts=[r"đường thẳng.", r"đường tròn.", r"đường hypebol.", r"đường parabol."], ans=0,
         sol=[r"Chuyển động thẳng đều có $d = vt$ là hàm bậc nhất của $t$ nên đồ thị $(d - t)$ là một đường thẳng."]),
    dict(stem=r"Một vật chuyển động thẳng biến đổi đều với vận tốc ban đầu $v_0$, sau thời gian $t$ vật có vận tốc $v$. Gia tốc của vật là",
         opts=[r"$a = \dfrac{v_0 - v}{t}$", r"$a = \dfrac{v_0 + v}{t}$", r"$a = \dfrac{v^2 - v_0^2}{t}$", r"$a = \dfrac{v - v_0}{t}$"], ans=3,
         sol=[r"Theo định nghĩa: $a = \dfrac{\Delta v}{\Delta t} = \dfrac{v - v_0}{t}$."]),
    dict(stem=r"Một chất điểm đi được quãng đường $s$ trong khoảng thời gian $\Delta t$. Tốc độ trung bình của chất điểm là",
         opts=[r"$v_{\text{tb}} = s \cdot \Delta t$", r"$v_{\text{tb}} = s - \Delta t$", r"$v_{\text{tb}} = \dfrac{s}{\Delta t}$", r"$v_{\text{tb}} = \dfrac{\Delta t}{s}$"], ans=2,
         sol=[r"Tốc độ trung bình bằng quãng đường chia thời gian: $v_{\text{tb}} = \dfrac{s}{\Delta t}$."]),
    dict(stem=r"Độ dịch chuyển của một vật cho biết",
         opts=[r"độ dài và hướng của sự thay đổi vị trí của vật.", r"vị trí và thời điểm chuyển động của vật.",
               r"mức độ nhanh hay chậm của chuyển động.", r"tổng độ dài quãng đường mà vật đã đi được."], ans=0,
         sol=[r"Độ dịch chuyển $\vec{d}$ là vectơ nối vị trí đầu với vị trí cuối, cho biết độ dài (khoảng cách thẳng) và hướng của sự thay đổi vị trí của vật."]),
    dict(stem=r"Khi phòng thực hành xảy ra sự cố cháy, hành động nào sau đây là \textbf{sai}?",
         opts=[r"Ngắt ngay toàn bộ nguồn điện của phòng thực hành.",
               r"Di chuyển nhanh các chai lọ hóa chất, vật liệu dễ cháy ra khu vực an toàn.",
               r"Không dùng bình khí $\text{CO}_2$ để dập đám cháy trên quần áo người hoặc đám cháy kim loại kiềm.",
               r"Dùng nước dội trực tiếp để dập đám cháy ở nơi có thiết bị điện đang cắm nguồn."], ans=3,
         sol=[r"Nước dẫn điện, dội nước vào đám cháy có thiết bị điện đang cắm nguồn có thể gây chập điện, điện giật cho người chữa cháy. Đây là hành động sai."]),
]

P2 = [
    dict(stem=r"Một bạn học sinh đạp xe từ cổng trường THPT Chuyên Quốc Học Huế đi thẳng theo đường Lê Lợi $1\text{ km}$, sau đó rẽ phải vào đường Hùng Vương đi thẳng $500\text{ m}$ để đến quán chè Hẻm như sơ đồ hình bên. Coi hai đoạn đường vuông góc với nhau.",
         fig=("fig_cau13", 5.6),
         items=[r"Quãng đường đi được và độ lớn độ dịch chuyển của bạn học sinh là khác nhau.",
                r"Độ dịch chuyển của bạn học sinh là một đại lượng vô hướng.",
                r"Quãng đường bạn học sinh đã đi được là $1{,}5\text{ km}$.",
                r"Độ lớn độ dịch chuyển của bạn học sinh bằng $1180\text{ m}$."],
         truth=[True, False, True, False],
         sols=[r"Đường đi gấp khúc (có rẽ) nên quãng đường lớn hơn độ lớn độ dịch chuyển.",
               r"Độ dịch chuyển là đại lượng vectơ, có cả độ lớn và hướng.",
               r"$s = 1000 + 500 = 1500\text{ m} = 1{,}5\text{ km}$.",
               r"Hai đoạn vuông góc: $d = \sqrt{1000^2 + 500^2} \approx 1118\text{ m} \ne 1180\text{ m}$."]),
    dict(stem=r"Một vật chuyển động thẳng dọc theo trục $Ox$ có phương trình độ dịch chuyển $d = 4t - t^2$ ($d$ tính bằng m, $t$ tính bằng s, $t \ge 0$).",
         items=[r"Vật chuyển động thẳng nhanh dần đều trong suốt quá trình chuyển động.",
                r"Ngay sau thời điểm $t = 0$, vật chuyển động theo chiều dương của trục $Ox$.",
                r"Gia tốc của vật bằng $1\text{ m/s}^2$.",
                r"Vận tốc của vật tại thời điểm $t = 1\text{ s}$ bằng $2\text{ m/s}$."],
         truth=[False, True, False, True],
         sols=[r"So sánh với $d = v_0t + \dfrac{1}{2}at^2$: $v_0 = 4\text{ m/s}$, $a = -2\text{ m/s}^2$. Ban đầu $a \cdot v_0 < 0$ nên vật chuyển động chậm dần đều (đến $t = 2\text{ s}$ thì đổi chiều).",
               r"$v_0 = 4\text{ m/s} > 0$ nên ban đầu vật chuyển động theo chiều dương.",
               r"$a = -2\text{ m/s}^2 \ne 1\text{ m/s}^2$.",
               r"$v = v_0 + at = 4 - 2t \Rightarrow v(1) = 4 - 2 \cdot 1 = 2\text{ m/s}$."]),
]

P3 = [
    dict(stem=r"Tại giải vô địch điền kinh thế giới ở Berlin (Đức), vận động viên Usain Bolt lập kỉ lục thế giới chạy $100\text{ m}$ với thời gian $9{,}58\text{ s}$. Tốc độ trung bình của Usain Bolt trên đường chạy đó là bao nhiêu $\text{m/s}$? (Làm tròn kết quả đến chữ số hàng phần mười).",
         ans="10,4",
         sol=[r"\[v_{\text{tb}} = \frac{s}{\Delta t} = \frac{100}{9{,}58} \approx 10{,}44 \approx 10{,}4\text{ m/s}.\]"]),
    dict(stem=r"Hình bên là đồ thị độ dịch chuyển -- thời gian $(d - t)$ của một ô tô chuyển động thẳng. Vận tốc của ô tô bằng bao nhiêu $\text{m/s}$?",
         fig=("fig_cau16", 5.6), ans="5",
         sol=[r"Đồ thị là đường thẳng qua gốc tọa độ nên ô tô chuyển động thẳng đều. Tại $t = 5\text{ h}$ thì $d = 90\text{ km}$:",
              r"\[v = \frac{d}{t} = \frac{90}{5} = 18\text{ km/h} = \frac{18}{3{,}6} = 5\text{ m/s}.\]"]),
    dict(stem=r"Một người đang lái xe máy với tốc độ $28{,}8\text{ km/h}$ thì nhìn thấy một cái hố trước mặt nên hãm phanh, xe chuyển động chậm dần đều và dừng lại sau $5\text{ s}$. Chọn chiều dương là chiều chuyển động. Gia tốc của xe là bao nhiêu $\text{m/s}^2$?",
         ans="-1,6",
         sol=[r"$v_0 = 28{,}8\text{ km/h} = 8\text{ m/s}$; $v = 0$.",
              r"\[a = \frac{v - v_0}{\Delta t} = \frac{0 - 8}{5} = -1{,}6\text{ m/s}^2.\]"]),
    dict(stem=r"Một vật được thả rơi tự do từ độ cao $80\text{ m}$ so với mặt đất. Lấy $g = 10\text{ m/s}^2$. Thời gian rơi của vật là bao nhiêu giây?",
         ans="4",
         sol=[r"\[h = \frac{1}{2}gt^2 \Rightarrow t = \sqrt{\frac{2h}{g}} = \sqrt{\frac{2 \cdot 80}{10}} = 4\text{ s}.\]"]),
]

P4 = [
    dict(stem=r"Lúc 7 giờ, một ô tô chuyển động thẳng đều với tốc độ $40\text{ km/h}$ đi từ $A$ qua $B$ đến $C$. Biết $AB = 30\text{ km}$, $BC = 70\text{ km}$ ($A$, $B$, $C$ thẳng hàng theo thứ tự đó). Chọn gốc tọa độ tại $A$, chiều dương từ $A$ đến $B$, gốc thời gian lúc 7 giờ. Vẽ đồ thị độ dịch chuyển -- thời gian $(d - t)$ của ô tô.",
         parts=[],
         sol=[r"Phương trình độ dịch chuyển: $d = vt = 40t$ ($d$: km, $t$: h).",
              r"-- Tại $A$: $t = 0$, $d = 0$.",
              r"-- Tại $B$: $d_B = 30\text{ km} \Rightarrow t_B = \dfrac{30}{40} = 0{,}75\text{ h}$ (lúc 7 giờ 45 phút).",
              r"-- Tại $C$: $d_C = 30 + 70 = 100\text{ km} \Rightarrow t_C = \dfrac{100}{40} = 2{,}5\text{ h}$ (lúc 9 giờ 30 phút).",
              r"Đồ thị là đoạn thẳng đi qua $O(0; 0)$, $B(0{,}75; 30)$ và kết thúc tại $C(2{,}5; 100)$:"],
         solfig=("fig_cau19_giai", 7.0)),
    dict(stem=r"Một vật chuyển động thẳng biến đổi đều dọc theo trục $Ox$ có đồ thị vận tốc -- thời gian $(v - t)$ như hình bên. Tính:",
         fig=("fig_cau20", 5.2),
         parts=[r"Gia tốc của vật.", r"Quãng đường vật đi được trong $10\text{ s}$ đầu tiên."],
         sol=[r"\textbf{a)} Từ đồ thị: $v_0 = 2\text{ m/s}$, tại $t = 10\text{ s}$ thì $v = 12\text{ m/s}$.",
              r"\[a = \frac{v - v_0}{t} = \frac{12 - 2}{10} = 1\text{ m/s}^2.\]",
              r"\textbf{b)} Vật chuyển động theo một chiều ($v > 0$) nên quãng đường bằng độ dịch chuyển:",
              r"\[s = v_0t + \frac{1}{2}at^2 = 2 \cdot 10 + \frac{1}{2} \cdot 1 \cdot 10^2 = 70\text{ m}.\]",
              r"(Hoặc tính diện tích hình thang dưới đồ thị: $s = \dfrac{(2 + 12) \cdot 10}{2} = 70\text{ m}$.)"]),
    dict(stem=r"Thả rơi tự do một vật từ độ cao $100\text{ m}$ so với mặt đất. Lấy $g = 10\text{ m/s}^2$. Tính:",
         parts=[r"Quãng đường vật rơi được sau $3\text{ s}$ kể từ lúc thả.", r"Độ cao của vật so với mặt đất tại thời điểm đó."],
         sol=[r"\textbf{a)} \[s = \frac{1}{2}gt^2 = \frac{1}{2} \cdot 10 \cdot 3^2 = 45\text{ m}.\]",
              r"\textbf{b)} Độ cao của vật so với mặt đất: $h' = h - s = 100 - 45 = 55\text{ m}$."]),
]

if __name__ == "__main__":
    E.run(dict(FOLDER="BTX_10", MADE="207", PREFIX="VL10_BTX", SCHOOL="THPT BÙI THỊ XUÂN",
               YEAR="2025 -- 2026", YEAR_W="2025 – 2026", P1=P1, P2=P2, P3=P3, P4=P4))
