# -*- coding: utf-8 -*-
"""ĐỀ KIỂM TRA GIỮA KỲ I - VẬT LÍ 10 - THPT NGUYỄN HUỆ (HUẾ) - MÃ ĐỀ 494
Nguồn: De_Goc/2026-Dethi-GHK1-10/VL10-GHKI-NH-2526.tex
Bản quyền: LỚP TOÁN CÔ THÚY - GV: HỒ THỊ THÚY"""
import vl10_engine as E

P1 = [
    dict(stem=r"Một vật rơi tự do, sau $3\text{ s}$ kể từ khi bắt đầu rơi, vận tốc của vật là bao nhiêu? (Lấy $g = 9{,}8\text{ m/s}^2$).",
         opts=[r"$29{,}4\text{ m/s}$.", r"$4{,}9\text{ m/s}$.", r"$19{,}8\text{ m/s}$.", r"$39{,}2\text{ m/s}$."], ans=0,
         sol=[r"Vận tốc của vật rơi tự do từ trạng thái nghỉ sau thời gian $t$ là:",
              r"\[v = gt = 9{,}8 \cdot 3 = 29{,}4\text{ m/s}.\]"]),
    dict(stem=r"Đối tượng nghiên cứu cốt lõi của Vật lí học tập trung chủ yếu vào",
         opts=[r"các dạng vận động của vật chất và các dạng năng lượng trong tự nhiên.",
               r"vật lí nguyên tử và cấu trúc các hạt nhân.",
               r"các dạng vận động sinh học của phân tử sinh vật và năng lượng sống.",
               r"các phân môn Cơ học, Nhiệt học, Điện học, Quang học cổ điển."], ans=0,
         sol=[r"Đối tượng nghiên cứu của Vật lí học bao gồm các dạng vận động cơ bản của vật chất (cơ, nhiệt, điện, từ, quang, hạt nhân,...) và các dạng năng lượng tương tác giữa chúng trong tự nhiên."]),
    dict(stem=r"Trong thí nghiệm đo tốc độ chuyển động thẳng của xe lăn trên máng đỡ, học sinh dùng cảm biến thời gian và thước đo quãng đường. Kết quả đo được: xe đi được quãng đường $s = 0{,}50\text{ m}$ trong thời gian $t = 1{,}25\text{ s}$. Tốc độ trung bình của xe là",
         opts=[r"$0{,}25\text{ m/s}$.", r"$0{,}40\text{ m/s}$.", r"$0{,}60\text{ m/s}$.", r"$0{,}50\text{ m/s}$."], ans=1,
         sol=[r"Tốc độ trung bình của xe lăn:",
              r"\[v_{\text{tb}} = \frac{s}{t} = \frac{0{,}50}{1{,}25} = 0{,}40\text{ m/s}.\]"]),
    dict(stem=r"Kết luận nào sau đây là \textbf{sai} khi nói về độ dịch chuyển của một vật chuyển động?",
         opts=[r"Khi vật chuyển động thẳng, không đổi chiều thì độ lớn của độ dịch chuyển bằng quãng đường đi được ($d = s$).",
               r"Khi vật chuyển động thẳng, có đổi chiều thì độ lớn của độ dịch chuyển bằng quãng đường đi được ($d = s$).",
               r"Độ dịch chuyển được biểu diễn bằng một mũi tên nối vị trí đầu và vị trí cuối của chuyển động.",
               r"Độ dịch chuyển có thể nhận giá trị dương, âm hoặc bằng $0$."], ans=1,
         sol=[r"Khi vật chuyển động thẳng có đổi chiều, quãng đường đi được lớn hơn độ lớn của độ dịch chuyển ($s > d$). Do đó kết luận B là sai."]),
    dict(stem=r"Trong thí nghiệm đo gia tốc rơi tự do, học sinh thả một quả bóng nhỏ từ độ cao $h = 1{,}20\text{ m}$. Thời gian rơi trung bình đo được là $t = 0{,}495\text{ s}$. Bỏ qua lực cản không khí. Giá trị gia tốc rơi tự do $g$ gần nhất với giá trị nào sau đây?",
         opts=[r"$9{,}79\text{ m/s}^2$.", r"$8{,}85\text{ m/s}^2$.", r"$9{,}02\text{ m/s}^2$.", r"$10{,}2\text{ m/s}^2$."], ans=0,
         sol=[r"Công thức rơi tự do: $h = \dfrac{1}{2}gt^2 \Rightarrow g = \dfrac{2h}{t^2}$.",
              r"\[g = \frac{2 \cdot 1{,}20}{(0{,}495)^2} \approx 9{,}795\text{ m/s}^2 \approx 9{,}79\text{ m/s}^2.\]"]),
    dict(stem=r"Hành động nào sau đây vi phạm nguyên tắc an toàn khi làm thí nghiệm thực hành Vật lí?",
         opts=[r"Không chạm tay vào các thiết bị điện khi đang hoạt động.",
               r"Chạm tay trực tiếp vào ổ điện, dây dẫn trần hoặc thiết bị điện đang hoạt động khi chưa ngắt nguồn.",
               r"Sau khi làm xong thí nghiệm phải tắt nguồn điện, rút phích cắm và dọn dẹp nơi làm việc.",
               r"Chỉ tiến hành thí nghiệm khi có sự cho phép và hướng dẫn của giáo viên."], ans=1,
         sol=[r"Chạm tay trực tiếp vào ổ điện, dây dẫn trần hoặc thiết bị chưa ngắt nguồn có nguy cơ gây điện giật nguy hiểm đến tính mạng, vi phạm nghiêm trọng quy tắc an toàn."]),
    dict(stem=r"Trong thí nghiệm đo các đại lượng vật lí, để giảm thiểu sai số ngẫu nhiên của phép đo, người ta thường",
         opts=[r"thực hiện phép đo lặp lại nhiều lần và tính giá trị trung bình.",
               r"chỉ đo một lần duy nhất để tiết kiệm thời gian.",
               r"giảm bớt khối lượng của vật làm thí nghiệm.",
               r"tăng khối lượng của vật làm thí nghiệm."], ans=0,
         sol=[r"Sai số ngẫu nhiên xuất hiện do các yếu tố ngẫu nhiên không kiểm soát được. Để giảm sai số ngẫu nhiên, ta cần lặp lại phép đo nhiều lần trong cùng điều kiện và tính giá trị trung bình."]),
    dict(stem=r"Một vật chuyển động thẳng nhanh dần đều từ trạng thái nghỉ ($v_0 = 0$). Sau thời gian $4\text{ s}$, vận tốc của vật đạt $10\text{ m/s}$. Gia tốc của chuyển động là",
         opts=[r"$2{,}5\text{ m/s}^2$.", r"$0{,}5\text{ m/s}^2$.", r"$5\text{ m/s}^2$.", r"$10\text{ m/s}^2$."], ans=0,
         sol=[r"Gia tốc của vật:",
              r"\[a = \frac{v - v_0}{t} = \frac{10 - 0}{4} = 2{,}5\text{ m/s}^2.\]"]),
    dict(stem=r"Vận tốc tức thời là một đại lượng vectơ đặc trưng cho",
         opts=[r"độ nhanh chậm và hướng chuyển động của vật tại một thời điểm xác định.",
               r"độ nhanh chậm của chuyển động, luôn nhận giá trị không âm.",
               r"quãng đường vật đi được trong một đơn vị thời gian.",
               r"chiều biến thiên của gia tốc."], ans=0,
         sol=[r"Vận tốc tức thời $\vec{v}$ là đại lượng vectơ, cho biết mức độ nhanh chậm và hướng chuyển động của vật tại thời điểm quan sát."]),
    dict(stem=r"Cặp đồ thị nào trong hình vẽ dưới đây biểu diễn đặc trưng cho chuyển động thẳng đều?",
         fig=("fig_cau10", 12.0),
         opts=[r"(II) và (III).", r"(I) và (IV).", r"(I) và (III).", r"(II) và (IV)."], ans=1,
         sol=[r"-- Trong chuyển động thẳng đều, $d = vt$ nên đồ thị $d - t$ là đường thẳng qua gốc tọa độ $\Rightarrow$ Đồ thị (I).",
              r"-- Vận tốc không đổi theo thời gian ($v = \text{const}$) nên đồ thị $v - t$ là đường thẳng song song trục thời gian $\Rightarrow$ Đồ thị (IV).",
              r"Vậy cặp đồ thị đúng là (I) và (IV)."]),
    dict(stem=r"Gia tốc của một chuyển động thẳng biến đổi là đại lượng đặc trưng cho",
         opts=[r"sự biến thiên nhanh hay chậm của vận tốc theo thời gian.",
               r"độ lớn của vận tốc tức thời.",
               r"tổng chiều dài quãng đường vật đi được.",
               r"hướng chuyển động của vật."], ans=0,
         sol=[r"Gia tốc $\vec{a} = \dfrac{\Delta \vec{v}}{\Delta t}$ đặc trưng cho tốc độ biến thiên của vectơ vận tốc theo thời gian."]),
    dict(stem=r"Sai số tỉ đối $\delta A$ của phép đo đại lượng vật lí $A$ được xác định theo công thức nào?",
         opts=[r"$\delta A = \dfrac{\Delta A}{\overline{A}} \cdot 100\%$.",
               r"$\delta A = |\overline{A} - A|$.",
               r"$\delta A = \Delta A \cdot 100\%$.",
               r"$\delta A = \dfrac{A}{\overline{A}} \cdot 100\%$."], ans=0,
         sol=[r"Sai số tỉ đối là tỉ số phần trăm giữa sai số tuyệt đối toàn phần $\Delta A$ và giá trị trung bình $\overline{A}$: $\delta A = \dfrac{\Delta A}{\overline{A}} \cdot 100\%$."]),
]

P2 = [
    dict(stem=r"Một vật chuyển động thẳng đều dọc theo trục $Ox$.",
         items=[r"Vectơ vận tốc của vật luôn cùng hướng với hướng chuyển động của vật.",
                r"Vận tốc đại số có thể mang dấu âm hoặc dương, còn tốc độ luôn không âm.",
                r"Nếu vật chuyển động về phía đầu tàu với vận tốc $2\text{ m/s}$ so với sàn tàu, đồng thời đoàn tàu chạy với vận tốc $10\text{ m/s}$ so với đường ray (cùng chiều về hướng Đông), thì vận tốc của vật đối với mặt đường có độ lớn bằng $8\text{ m/s}$.",
                r"Tốc độ tức thời cho biết mức độ nhanh hay chậm của chuyển động tại thời điểm xét."],
         truth=[True, True, False, True],
         sols=[r"Vectơ vận tốc $\vec{v}$ luôn cùng hướng với chiều chuyển động của vật.",
               r"Vận tốc $v$ là đại lượng đại số phụ thuộc chiều dương đã chọn, còn tốc độ là độ lớn của vận tốc nên $v_{\text{tốc độ}} = |\vec{v}| \ge 0$.",
               r"Hai chuyển động cùng chiều nên áp dụng công thức cộng vận tốc: $v = v_1 + v_2 = 2 + 10 = 12\text{ m/s} \ne 8\text{ m/s}$.",
               r"Tốc độ tức thời đặc trưng cho mức độ nhanh chậm của chuyển động tại từng thời điểm."]),
    dict(stem=r"Một chất điểm chuyển động dọc theo một đường thẳng từ điểm $A$ đến điểm $B$.",
         items=[r"Khi chất điểm đi từ $A$ đến $B$ rồi quay về lại $A$, quãng đường đi được bằng $0$.",
                r"Độ lớn của độ dịch chuyển luôn luôn bằng quãng đường vật đi được trong mọi trường hợp.",
                r"Quãng đường đi được của chất điểm luôn lớn hơn hoặc bằng độ lớn độ dịch chuyển ($s \ge d$).",
                r"Nếu chất điểm đi thẳng từ $A$ đến $B$ ($AB = 5\text{ m}$) rồi quay ngược lại điểm $C$ ($BC = 2\text{ m}$), thì độ lớn độ dịch chuyển của vật bằng $3\text{ m}$."],
         truth=[False, False, True, True],
         sols=[r"Khi quay về vị trí ban đầu $A$, độ dịch chuyển bằng $0$ nhưng quãng đường $s = AB + BA = 2AB \ne 0$.",
               r"Độ lớn độ dịch chuyển chỉ bằng quãng đường khi vật chuyển động thẳng và không đổi chiều.",
               r"Độ dịch chuyển là khoảng cách thẳng nối điểm đầu và điểm cuối nên luôn có $s \ge d$.",
               r"Vật đi từ $A$ đến $B$ rồi quay lại $C$: điểm đầu là $A$, điểm cuối là $C$ nên độ dịch chuyển $d = AC = AB - BC = 5 - 2 = 3\text{ m}$."]),
]

P3 = [
    dict(stem=r"Một vật đi được quãng đường $0{,}6\text{ km}$ trong thời gian $2\text{ phút}$. Tốc độ trung bình của vật là bao nhiêu $\text{m/s}$?",
         ans="5",
         sol=[r"Đổi đơn vị: $s = 0{,}6\text{ km} = 600\text{ m}$, $t = 2\text{ phút} = 120\text{ s}$.",
              r"\[v_{\text{tb}} = \frac{s}{t} = \frac{600}{120} = 5\text{ m/s}.\]"]),
    dict(stem=r"Một ô tô đi thẳng từ $A$ đến $B$ cách $A$ một khoảng $300\text{ m}$, sau đó quay đầu chạy về $C$ cách $A$ một khoảng $100\text{ m}$ ($C$ nằm giữa $A$ và $B$). Tổng quãng đường ô tô đã đi được là bao nhiêu mét?",
         ans="500",
         sol=[r"Quãng đường chặng 1: $s_1 = AB = 300\text{ m}$.",
              r"Quãng đường chặng 2: $s_2 = BC = AB - AC = 300 - 100 = 200\text{ m}$.",
              r"\[s = s_1 + s_2 = 300 + 200 = 500\text{ m}.\]"]),
    dict(stem=r"Một ô tô đang chuyển động thẳng đều với vận tốc $8\text{ m/s}$ thì tăng tốc chuyển động thẳng nhanh dần đều. Sau $16\text{ s}$, vận tốc của xe đạt $12\text{ m/s}$. Quãng đường ô tô đi được kể từ lúc tăng tốc cho đến khi đạt vận tốc $16\text{ m/s}$ là bao nhiêu mét?",
         ans="384",
         sol=[r"Gia tốc của xe: $a = \dfrac{v_1 - v_0}{t_1} = \dfrac{12 - 8}{16} = 0{,}25\text{ m/s}^2$.",
              r"Áp dụng hệ thức độc lập thời gian từ lúc $v_0 = 8\text{ m/s}$ đến $v_2 = 16\text{ m/s}$:",
              r"\[v_2^2 - v_0^2 = 2as \Rightarrow 16^2 - 8^2 = 2 \cdot 0{,}25 \cdot s \Rightarrow 192 = 0{,}5s \Rightarrow s = 384\text{ m}.\]"]),
    dict(stem=r"Thả một vật rơi tự do từ độ cao $h$ so với mặt đất. Thời gian rơi chạm đất là $2\text{ s}$. Lấy $g = 9{,}8\text{ m/s}^2$. Độ cao $h$ bằng bao nhiêu mét?",
         ans="19,6",
         sol=[r"\[h = \frac{1}{2}gt^2 = \frac{1}{2} \cdot 9{,}8 \cdot 2^2 = 19{,}6\text{ m}.\]"]),
]

P4 = [
    dict(stem=r"Một chiếc xe máy chuyển động thẳng có đồ thị độ dịch chuyển -- thời gian $(d - t)$ như hình bên.",
         fig=("fig_cau19", 6.5),
         parts=[r"Nêu tính chất chuyển động của xe máy.",
                r"Tính vận tốc của xe máy."],
         sol=[r"\textbf{a)} Đồ thị $(d - t)$ là đường thẳng đi qua gốc tọa độ $O$, chứng tỏ độ dịch chuyển tăng tỉ lệ thuận với thời gian theo hàm bậc nhất. Do đó, xe máy chuyển động thẳng đều theo chiều dương.",
              r"\textbf{b)} Từ đồ thị, tại thời điểm $t = 4\text{ s}$ xe có độ dịch chuyển $d = 20\text{ m}$. Vận tốc của xe là:",
              r"\[v = \frac{d}{t} = \frac{20}{4} = 5\text{ m/s}.\]"]),
    dict(stem=r"Từ đỉnh một vách núi thẳng đứng, một người thả rơi tự do một hòn đá nhỏ xuống đáy vực sâu. Sau thời gian $9\text{ s}$ kể từ lúc thả, người đó nghe thấy tiếng đá chạm vào đáy vực. Biết vận tốc truyền âm trong không khí là $320\text{ m/s}$, lấy $g = 9{,}8\text{ m/s}^2$. Tính độ cao của đỉnh vách núi so với đáy vực (làm tròn đến hàng đơn vị mét).",
         parts=[],
         sol=[r"Gọi $h$ là độ cao của vách núi. Thời gian $9\text{ s}$ gồm hai giai đoạn:",
              r"-- Thời gian hòn đá rơi tự do xuống đáy vực: $t_1 = \sqrt{\dfrac{2h}{g}} = \sqrt{\dfrac{h}{4{,}9}}$.",
              r"-- Thời gian âm thanh truyền từ đáy vực lên tai người: $t_2 = \dfrac{h}{v_{\text{âm}}} = \dfrac{h}{320}$.",
              r"Phương trình tổng thời gian:",
              r"\[t_1 + t_2 = 9 \Rightarrow \sqrt{\frac{h}{4{,}9}} + \frac{h}{320} = 9.\]",
              r"Đặt $X = \sqrt{h} \ge 0$, phương trình trở thành:",
              r"\[\frac{1}{320}X^2 + \frac{1}{\sqrt{4{,}9}}X - 9 = 0.\]",
              r"Giải phương trình bậc hai ta được nghiệm dương: $X \approx 17{,}49 \Rightarrow h = X^2 \approx 306\text{ m}$."]),
    dict(stem=r"Một vật bắt đầu chuyển động thẳng nhanh dần đều từ trạng thái nghỉ ($v_0 = 0$). Sau $3\text{ s}$, vật đi được quãng đường $9\text{ m}$. Hãy xác định:",
         parts=[r"Gia tốc của vật.",
                r"Thời gian kể từ lúc bắt đầu chuyển động để vật đạt vận tốc $15\text{ m/s}$."],
         sol=[r"\textbf{a)} Quãng đường vật đi được: $s = \dfrac{1}{2}at^2 \Rightarrow 9 = \dfrac{1}{2}a \cdot 3^2 = 4{,}5a \Rightarrow a = 2\text{ m/s}^2$.",
              r"\textbf{b)} Vận tốc tại thời điểm $t$: $v = at \Rightarrow 15 = 2t \Rightarrow t = 7{,}5\text{ s}$."]),
]

if __name__ == "__main__":
    E.run(dict(FOLDER="NH_10", MADE="494", PREFIX="VL10_NH", SCHOOL="THPT NGUYỄN HUỆ",
               YEAR="2025 -- 2026", YEAR_W="2025 – 2026", P1=P1, P2=P2, P3=P3, P4=P4))
