# -*- coding: utf-8 -*-
"""ĐỀ KIỂM TRA GIỮA KỲ I - VẬT LÍ 10 - THPT PHAN ĐĂNG LƯU (HUẾ) - MÃ ĐỀ 1008
Nguồn: De_Goc/2026-Dethi-GHK1-10/VL10-GHKI-PDL-2526.tex
Bản quyền: LỚP TOÁN CÔ THÚY - GV: HỒ THỊ THÚY"""
import vl10_engine as E

P1 = [
    dict(stem=r"Chuyển động nào sau đây là chuyển động biến đổi?",
         opts=[r"Chuyển động thẳng đều.",
               r"Chuyển động có độ dịch chuyển giảm đều theo thời gian.",
               r"Chuyển động tròn đều.",
               r"Chuyển động có độ dịch chuyển tăng đều theo thời gian."], ans=2,
         sol=[r"Chuyển động tròn đều tuy có tốc độ không đổi nhưng hướng của vectơ vận tốc liên tục thay đổi theo thời gian, do đó là chuyển động biến đổi."]),
    dict(stem=r"Đối tượng nghiên cứu tổng quát của khoa học Vật lí là",
         opts=[r"quy luật tương tác của các dạng năng lượng độc lập.",
               r"các dạng vận động của vật chất và các dạng năng lượng trong tự nhiên.",
               r"các dạng vận động và tương tác cơ học của vật chất vô cơ.",
               r"các quy luật nhiệt động lực học ứng dụng."], ans=1,
         sol=[r"Vật lí học tập trung nghiên cứu về các dạng vận động cơ bản của vật chất và các dạng năng lượng tương tác giữa chúng trong tự nhiên từ cấp vi mô đến vĩ mô."]),
    dict(stem=r"Một người đi xe máy từ nhà đến bến xe buýt cách nhà $6\text{ km}$ về phía Đông, sau đó lên xe buýt đi tiếp $6\text{ km}$ thẳng về phía Bắc. Độ lớn độ dịch chuyển tổng hợp của người này là",
         opts=[r"$6\text{ km}$.",
               r"$12\text{ km}$.",
               r"$72\text{ km}$.",
               r"$6\sqrt{2}\text{ km}$."], ans=3,
         sol=[r"Hai hướng chuyển động Đông và Bắc vuông góc với nhau.",
              r"Độ lớn độ dịch chuyển tổng hợp:",
              r"\[d = \sqrt{d_1^2 + d_2^2} = \sqrt{6^2 + 6^2} = 6\sqrt{2}\text{ km}.\]"]),
    dict(stem=r"Hành động nào sau đây \textbf{không} thuộc về phương pháp lí thuyết trong nghiên cứu Vật lí?",
         opts=[r"Thực hiện ném một quả bóng lên cao để quan sát quá trình chuyển động rơi.",
               r"Chế tạo quả địa cầu làm mô hình thu nhỏ của Trái Đất.",
               r"Biểu diễn đường truyền của chùm sáng bằng các tia sáng hình học.",
               r"Tính toán quỹ đạo chuyển động của các hành tinh dựa trên phương trình toán học."], ans=0,
         sol=[r"Hành động ném quả bóng để quan sát chuyển động thuộc về phương pháp thực nghiệm, không phải phương pháp lí thuyết hay mô hình hóa."]),
    dict(stem=r"Phát biểu nào sau đây \textbf{sai} khi nói về các cuộc cách mạng công nghiệp trong lịch sử?",
         opts=[r"Với cuộc cách mạng công nghiệp lần thứ hai, con người đã sản xuất được điện năng và đưa vào phục vụ sản xuất, đời sống.",
               r"Internet kết nối vạn vật, trí tuệ nhân tạo và công nghệ nano là các đặc trưng tiêu biểu của cách mạng công nghiệp lần thứ tư.",
               r"Đặc trưng cốt lõi của cuộc cách mạng công nghiệp lần thứ ba là thay thế sức cơ bắp của con người bằng máy móc cơ khí cơ bản.",
               r"Động cơ hơi nước do James Watt cải tiến năm 1769 là dấu mốc mở đầu cuộc cách mạng công nghiệp lần thứ nhất."], ans=2,
         sol=[r"Việc thay thế sức cơ bắp bằng máy móc cơ khí chạy bằng hơi nước là đặc trưng cốt lõi của cuộc cách mạng công nghiệp lần thứ nhất. Cách mạng công nghiệp lần thứ ba đặc trưng bởi tự động hóa và công nghệ thông tin."]),
    dict(stem=r"Phát biểu nào sau đây đúng khi nói về bản chất của đại lượng vận tốc tức thời?",
         opts=[r"Là đại lượng vectơ, cho biết mức độ nhanh chậm và hướng chuyển động của vật.",
               r"Là đại lượng vô hướng, cho biết tổng thời gian chuyển động của vật.",
               r"Là đại lượng vectơ, cho biết thời gian và quãng đường chuyển động của vật.",
               r"Là đại lượng vô hướng, chỉ cho biết mức độ nhanh chậm đơn thuần của chuyển động."], ans=0,
         sol=[r"Vận tốc tức thời $\vec{v}$ là đại lượng vectơ, có độ lớn cho biết mức độ nhanh chậm và có hướng cho biết hướng chuyển động của vật tại thời điểm xét."]),
    dict(stem=r"Một học sinh thực hành đo tốc độ của viên bi thép thu được kết quả: $v = 2{,}5 \pm 0{,}02\text{ (m/s)}$. Sai số tỉ đối $\delta v$ của phép đo này bằng",
         opts=[r"$0{,}2\%$.",
               r"$4{,}0\%$.",
               r"$0{,}8\%$.",
               r"$1{,}6\%$."], ans=2,
         sol=[r"Sai số tỉ đối của phép đo:",
              r"\[\delta v = \frac{\Delta v}{\overline{v}} \cdot 100\% = \frac{0{,}02}{2{,}5} \cdot 100\% = 0{,}8\%.\]"]),
    dict(stem=r"Độ dịch chuyển là một đại lượng vectơ cho biết",
         opts=[r"độ dài và hướng của sự thay đổi vị trí của vật.",
               r"tọa độ và hướng chuyển động tức thời của vật.",
               r"tổng chiều dài quãng đường thực tế mà vật đã đi được.",
               r"tốc độ trung bình trên toàn bộ hành trình của vật."], ans=0,
         sol=[r"Độ dịch chuyển $\vec{d}$ là vectơ nối vị trí đầu và vị trí cuối của vật, cho biết độ dài và hướng của sự thay đổi vị trí của vật."]),
    dict(stem=r"Ưu điểm nổi bật nhất của thiết bị cổng quang điện kết hợp với đồng hồ đo thời gian hiện số so với đồng hồ bấm giây cơ học là",
         opts=[r"có thể tự động đo được tất cả các đại lượng vật lí.",
               r"luôn cho kết quả đo nhanh nhất trong mọi tình huống.",
               r"loại bỏ được sai số chủ quan của con người khi bấm nút và có độ chính xác rất cao.",
               r"thiết bị có cấu tạo thô sơ và giá thành rẻ hơn."], ans=2,
         sol=[r"Cổng quang điện tự động kích hoạt và ngắt tín hiệu khi vật chắn chùm sáng, loại bỏ hoàn toàn sai số phản xạ chủ quan của người bấm đồng hồ cơ học, đem lại độ chính xác cao."]),
    dict(stem=r"Chọn phát biểu \textbf{không} đúng về các quy tắc an toàn trong phòng thực hành Vật lí.",
         opts=[r"Chọn sai thang đo khi dùng đồng hồ đo điện có thể làm hỏng hoặc chập cháy thiết bị.",
               r"Chỉ cần sử dụng thiết bị đo có lớp vỏ bằng nhựa hoặc kim loại thì sẽ tuyệt đối an toàn.",
               r"Đun nóng hóa chất dễ cháy bằng thiết bị điện công suất lớn có thể dẫn đến nguy cơ hỏa hoạn.",
               r"Thao tác sai quy trình kĩ thuật có thể dẫn đến tai nạn, chấn thương cho người làm thí nghiệm."], ans=1,
         sol=[r"Vỏ cách điện chỉ là biện pháp bảo vệ cơ bản, việc đảm bảo an toàn tuyệt đối phụ thuộc vào việc tuân thủ đúng quy trình kĩ thuật và quy tắc an toàn khi vận hành nguồn điện."]),
    dict(stem=r"Khi phát hiện sự cố chập điện gây cháy trong phòng thực hành Vật lí, thứ tự các hành động xử lí đúng là",
         opts=[r"dùng nước dội trực tiếp ngay vào đám cháy.",
               r"ngắt ngay cầu dao điện toàn khu, sơ tán vật dễ cháy ra xa, cứu người và tài sản, dập tắt đám cháy bằng bình chuyên dụng.",
               r"hô hoán rồi chạy nhanh ra ngoài mà không làm gì thêm.",
               r"chỉ ngắt nguồn điện rồi dùng nước dội vào đám cháy."], ans=1,
         sol=[r"Phải ngắt ngay nguồn điện trước tiên để tránh nguy cơ điện giật và chập cháy lan, sau đó sơ tán chất dễ cháy, cứu hộ và dập lửa bằng bình chữa cháy thích hợp (như bình bột hoặc bình khí $\text{CO}_2$)."]),
    dict(stem=r"Gọi $\overline{A}$ là giá trị trung bình và $\Delta A$ là sai số tuyệt đối toàn phần của phép đo đại lượng $A$. Sai số tỉ đối $\delta A$ được xác định theo công thức nào?",
         opts=[r"$\delta A = \dfrac{\Delta A}{\overline{A}} \cdot 100\%$.",
               r"$\delta A = \dfrac{\overline{A}}{\Delta A} \cdot 100\%$.",
               r"$\delta A = \Delta A \cdot \overline{A} \cdot 100\%$.",
               r"$\delta A = \dfrac{\Delta A}{\overline{A}}$."], ans=0,
         sol=[r"Sai số tỉ đối $\delta A$ là tỉ số phần trăm giữa sai số tuyệt đối và giá trị trung bình: $\delta A = \dfrac{\Delta A}{\overline{A}} \cdot 100\%$."]),
]

P2 = [
    dict(stem=r"Một học sinh dùng panme có sai số dụng cụ $0{,}01\text{ mm}$ để đo đường kính $d$ của một viên bi thép nhỏ. Kết quả qua 5 lần đo được ghi trong bảng sau:",
         items=[r"Muốn đánh giá mức độ chính xác của phép đo, ta căn cứ vào giá trị sai số tỉ đối của phép đo đó.",
                r"Bán kính trung bình của viên bi thép thu được từ chuỗi phép đo bằng $6{,}49\text{ mm}$.",
                r"Kết quả phép đo đường kính kèm sai số toàn phần được viết là $d = 6{,}49 \pm 0{,}03\text{ (mm)}$.",
                r"Phương pháp dùng panme để xác định trực tiếp đường kính viên bi là một phép đo gián tiếp."],
         truth=[True, False, True, False],
         sols=[r"Sai số tỉ đối phản ánh mức độ chính xác của phép đo: sai số tỉ đối càng nhỏ thì phép đo càng chính xác.",
               r"Giá trị trung bình từ bảng là đường kính trung bình: $\overline{d} = \dfrac{6{,}47 + 6{,}48 + 6{,}51 + 6{,}47 + 6{,}52}{5} = 6{,}49\text{ mm}$, không phải bán kính.",
               r"Sai số ngẫu nhiên: $\overline{\Delta d} = \dfrac{0{,}02 + 0{,}01 + 0{,}02 + 0{,}02 + 0{,}03}{5} = 0{,}02\text{ mm}$. Sai số toàn phần: $\Delta d = \overline{\Delta d} + \Delta d_{\text{dc}} = 0{,}02 + 0{,}01 = 0{,}03\text{ mm}$. Kết quả đúng: $d = 6{,}49 \pm 0{,}03\text{ mm}$.",
               r"Đường kính viên bi được đọc trực tiếp từ thang chia của panme nên đây là phép đo trực tiếp."]),
    dict(stem=r"Một vật bắt đầu chuyển động thẳng nhanh dần đều trên phương ngang từ trạng thái nghỉ ($v_0 = 0$). Sau khi đi được quãng đường $100\text{ m}$ đầu tiên, vật đạt tốc độ $20\text{ m/s}$. Chọn chiều dương là chiều chuyển động của vật.",
         items=[r"Trong hệ SI, đơn vị đo tiêu chuẩn của gia tốc là mét trên giây ($\text{m/s}$).",
                r"Vận tốc tức thời của vật sau thời gian $t = 5\text{ s}$ kể từ lúc xuất phát bằng $15\text{ m/s}$.",
                r"Vì vật chuyển động nhanh dần đều nên gia tốc $a$ và vận tốc tức thời $v$ luôn cùng dấu đại số.",
                r"Gia tốc của chuyển động này có giá trị đại số là $a = -2\text{ m/s}^2$."],
         truth=[False, False, True, False],
         sols=[r"Đơn vị tiêu chuẩn của gia tốc trong hệ SI là mét trên giây bình phương ($\text{m/s}^2$).",
               r"Áp dụng hệ thức: $v^2 - v_0^2 = 2as \Rightarrow 20^2 - 0 = 2 \cdot a \cdot 100 \Rightarrow a = 2\text{ m/s}^2$. Sau $5\text{ s}$: $v = at = 2 \cdot 5 = 10\text{ m/s} \ne 15\text{ m/s}$.",
               r"Chuyển động thẳng nhanh dần đều có $a \cdot v > 0$ nên $a$ và $v$ luôn cùng dấu.",
               r"Vật chuyển động nhanh dần theo chiều dương nên gia tốc có giá trị dương: $a = +2\text{ m/s}^2$."]),
]

P3 = [
    dict(stem=r"Trong một đợt cứu hộ lũ lụt, ca nô chạy xuôi dòng nước với tốc độ $8\text{ m/s}$ so với dòng nước. Vận tốc dòng nước chảy đối với bờ sông là $4\text{ m/s}$. Khoảng cách từ trạm xuất phát đến vị trí người cần cứu nạn là $3\text{ km}$. Tính thời gian (theo đơn vị giây) để ca nô tiếp cận vị trí người cần cứu nạn?",
         ans="250",
         sol=[r"Đổi khoảng cách: $s = 3\text{ km} = 3000\text{ m}$.",
              r"Vận tốc của ca nô đối với bờ khi xuôi dòng:",
              r"\[v = v_{\text{cn/n}} + v_{\text{n/b}} = 8 + 4 = 12\text{ m/s}.\]",
              r"Thời gian chuyển động của ca nô:",
              r"\[t = \frac{s}{v} = \frac{3000}{12} = 250\text{ s}.\]"]),
    dict(stem=r"Một ô tô đứng yên bắt đầu chuyển động thẳng nhanh dần đều từ trạng thái nghỉ. Trong giây thứ 5 kể từ lúc xuất phát, xe đi được quãng đường $13{,}5\text{ m}$. Gia tốc của ô tô bằng bao nhiêu $\text{m/s}^2$?",
         ans="3",
         sol=[r"Quãng đường ô tô đi được trong giây thứ 5:",
              r"\[\Delta s_5 = s(5) - s(4) = \frac{1}{2}a \cdot 5^2 - \frac{1}{2}a \cdot 4^2 = \frac{9}{2}a = 4{,}5a\text{ (m)}.\]",
              r"Thay $\Delta s_5 = 13{,}5\text{ m}$:",
              r"\[13{,}5 = 4{,}5a \Rightarrow a = 3\text{ m/s}^2.\]"]),
    dict(stem=r"Một ô tô chuyển động thẳng đều có đồ thị độ dịch chuyển -- thời gian $(d - t)$ là đường thẳng đi qua gốc tọa độ $O$. Tại thời điểm $t = 2\text{ h}$, độ dịch chuyển của xe là $80\text{ km}$. Vận tốc của ô tô bằng bao nhiêu $\text{km/h}$?",
         ans="40",
         sol=[r"Vận tốc của chuyển động thẳng đều:",
              r"\[v = \frac{d}{t} = \frac{80}{2} = 40\text{ km/h}.\]"]),
    dict(stem=r"Một xe máy chuyển động thẳng nhanh dần đều từ trạng thái nghỉ ($v_0 = 0$). Sau khi đi được quãng đường $100\text{ m}$ đầu tiên, xe đạt vận tốc $10\text{ m/s}$. Vận tốc của xe sau khi đi thêm được quãng đường $100\text{ m}$ tiếp theo là bao nhiêu $\text{m/s}$? (Làm tròn kết quả đến một chữ số thập phân).",
         ans="14,1",
         sol=[r"Gia tốc của xe trên $100\text{ m}$ đầu:",
              r"\[v_1^2 - v_0^2 = 2as_1 \Rightarrow 10^2 - 0 = 2 \cdot a \cdot 100 \Rightarrow a = 0{,}5\text{ m/s}^2.\]",
              r"Tổng quãng đường xe đi được sau hai chặng: $S = s_1 + s_2 = 100 + 100 = 200\text{ m}$.",
              r"Vận tốc tại thời điểm đó:",
              r"\[v_2^2 - v_0^2 = 2aS \Rightarrow v_2 = \sqrt{2 \cdot 0{,}5 \cdot 200} = \sqrt{200} = 10\sqrt{2} \approx 14{,}1\text{ m/s}.\]"]),
]

P4 = [
    dict(stem=r"Một vận động viên bơi ngang từ bờ sông bên này sang bờ bên kia theo phương vuông góc với dòng sông rộng $50\text{ m}$ (hướng từ Tây sang Đông). Nước sông chảy theo hướng từ Bắc xuống Nam khiến người đó bị cuốn trôi xuôi về phía hạ lưu một đoạn $50\text{ m}$.",
         parts=[r"Vẽ hình minh họa và xác định hướng của vectơ độ dịch chuyển tổng hợp của người đó.",
                r"Tính độ lớn của độ dịch chuyển tổng hợp."],
         fig=("fig_nguoi_boi", 7.0),
         sol=[r"\textbf{a)} Minh họa chuyển động:",
              r"-- Chọn gốc $A$ tại vị trí xuất phát ở bờ bên này. Vectơ $\vec{d}_1 = \vec{AB}$ hướng sang bờ đối diện biểu diễn độ rộng dòng sông ($AB = 50\text{ m}$).",
              r"-- Vectơ $\vec{d}_2 = \vec{BC}$ hướng theo dòng nước chảy dọc bờ sông ($BC = 50\text{ m}$).",
              r"-- Vectơ độ dịch chuyển tổng hợp là $\vec{d} = \vec{AC} = \vec{d}_1 + \vec{d}_2$. Vectơ này có hướng Đông -- Nam, lệch góc $45^\circ$ so với phương bơi ban đầu.",
              r"\textbf{b)} Do $\vec{d}_1 \perp \vec{d}_2$, áp dụng định lí Pythagore:",
              r"\[d = AC = \sqrt{AB^2 + BC^2} = \sqrt{50^2 + 50^2} = 50\sqrt{2} \approx 70{,}71\text{ m}.\]"]),
    dict(stem=r"Một chất điểm chuyển động thẳng dọc theo trục $Ox$ có đồ thị vận tốc -- thời gian $(v - t)$ như hình bên.",
         fig=("fig_dothi_vt", 7.5),
         parts=[r"Tính độ biến thiên vận tốc $\Delta v$ của chất điểm từ thời điểm $t = 0$ đến thời điểm $t = 20\text{ s}$.",
                r"Tính gia tốc $a$ của chất điểm trong giai đoạn $CD$ (từ $t = 40\text{ s}$ đến $t = 80\text{ s}$)."],
         sol=[r"\textbf{a)} Từ đồ thị, tại thời điểm $t = 0$ có $v_A = 20\text{ cm/s}$; tại thời điểm $t = 20\text{ s}$ có $v_B = 60\text{ cm/s}$.",
              r"Độ biến thiên vận tốc trong giai đoạn $AB$:",
              r"\[\Delta v = v_B - v_A = 60 - 20 = 40\text{ cm/s} = 0{,}4\text{ m/s}.\]",
              r"\textbf{b)} Trong giai đoạn $CD$, tại $t_C = 40\text{ s}$ có $v_C = 60\text{ cm/s}$; tại $t_D = 80\text{ s}$ có $v_D = 0$.",
              r"Gia tốc của chất điểm trên đoạn $CD$:",
              r"\[a_{CD} = \frac{v_D - v_C}{t_D - t_C} = \frac{0 - 60}{80 - 40} = -1{,}5\text{ cm/s}^2 = -0{,}015\text{ m/s}^2.\]"]),
]

if __name__ == "__main__":
    E.run(dict(FOLDER="PDL_10", MADE="1008", PREFIX="VL10_PDL", SCHOOL="THPT PHAN ĐĂNG LƯU",
               YEAR="2025 -- 2026", YEAR_W="2025 – 2026", P1=P1, P2=P2, P3=P3, P4=P4))
